export const bookingContent = {
  en: {
    heading: 'Choose the kind of support that fits what you need right now',
    cards: [
      {
        key: 'intro',
        title: 'Free intro call',
        meta: '30 min · EUR 0',
        description: 'A calm 30-minute conversation where we can get to know each other, talk about what you need and see whether coaching or mentoring feels like the right form of support. No obligation — simply a chance to meet.',
        action: 'Enquire',
      },
      {
        key: 'coaching',
        title: 'Single coaching session',
        meta: '60–80 min · EUR 70',
        description: 'Is there something that needs your attention right now? A one-off coaching session gives you space to pause, untangle your thoughts and listen more closely for your own answers.',
        action: 'Enquire',
      },
      {
        key: 'mentoring',
        title: 'Single mentoring session',
        meta: '60–80 min · EUR 70',
        description: 'Bring a topic where my experience and perspective may be useful. I will share knowledge, practical guidance and lessons from my own experience that may help you look at your situation differently.',
        action: 'Enquire',
      },
      {
        key: 'cv',
        title: 'CV and cover letter review',
        meta: 'EUR 50',
        description: 'Your CV is often your first meeting with a potential employer. Let’s make sure it tells your professional story well. I will review your documents from an HR perspective and show you how to communicate your experience, strengths and value more effectively.',
        action: 'Enquire',
      },
      {
        key: 'linkedin',
        title: 'LinkedIn profile review',
        meta: 'EUR 50',
        description: 'Your LinkedIn profile can be much more than an online business card. I will look at it through a recruiter’s eyes and suggest how to make it communicate more effectively who you are and what you can offer.',
        action: 'Enquire',
      },
      {
        key: 'interview',
        title: 'Individual interview preparation',
        meta: '90–150 min · EUR 150',
        description: 'Have you got an interview coming up? Let’s prepare so that you can walk into it with more calm, confidence and awareness of your value. We will combine a coaching approach with my experience in HR and recruitment.',
        action: 'Enquire',
      },
    ],
    packages: {
      eyebrow: 'PACKAGES',
      title: 'Session packages',
      description: 'If you feel you want to give a change more time and space, choose a package that matches your needs. You decide how many sessions feel right for you and select the corresponding option.',
      coachingLabel: 'Coaching package',
      mentoringLabel: 'Mentoring package',
      sessionsLabel: 'sessions',
      action: 'Enquire',
      coaching: [
        { count: 2, price: 130 },
        { count: 3, price: 190 },
        { count: 4, price: 250 },
        { count: 5, price: 300 },
      ],
      mentoring: [
        { count: 2, price: 130 },
        { count: 3, price: 190 },
        { count: 4, price: 250 },
        { count: 5, price: 300 },
      ],
    },
  },

  pl: {
    heading: 'Wybierz formę wsparcia odpowiednią dla siebie',
    cards: [
      {
        key: 'intro',
        title: 'Bezpłatna rozmowa wstępna',
        meta: '30 min · 0 EUR',
        description: '30 minut spokojnej rozmowy, podczas której poznam Twoje potrzeby i razem sprawdzimy, czy coaching lub mentoring będzie dla Ciebie odpowiednią formą wsparcia. Bez zobowiązań – po prostu poznajmy się.',
        action: 'Zapytaj',
      },
      {
        key: 'coaching',
        title: 'Pojedyncza sesja coachingowa',
        meta: '60–80 min · 50 EUR',
        description: 'Masz temat, który potrzebujesz przeanalizować właśnie teraz? Umów pojedynczą, około 60-minutową sesję i daj sobie przestrzeń na zatrzymanie, uporządkowanie myśli i znalezienie własnych odpowiedzi.',
        action: 'Zapytaj',
      },
      {
        key: 'mentoring',
        title: 'Pojedyncza sesja mentoringowa',
        meta: '60–80 min · 50 EUR',
        description: 'Skorzystaj z mojego doświadczenia i perspektywy w obszarze, który jest dla Ciebie ważny. Podzielę się wiedzą, praktycznymi wskazówkami i własnymi doświadczeniami, które mogą pomóc Ci spojrzeć na swoją sytuację z innej perspektywy.',
        action: 'Zapytaj',
      },
      {
        key: 'cv',
        title: 'Analiza CV i listu motywacyjnego',
        meta: '50 EUR',
        description: 'Twoje CV to pierwsze spotkanie z potencjalnym pracodawcą – zadbajmy o to, aby dobrze opowiadało Twoją historię. Przyjrzę się Twoim dokumentom z perspektywy HR i podpowiem, jak w najbardziej efektywny sposób pokazać Twoje doświadczenie, kompetencje i wartość.',
        action: 'Zapytaj',
      },
      {
        key: 'linkedin',
        title: 'Analiza profilu na LinkedIn',
        meta: '50 EUR',
        description: 'Twój profil na LinkedIn może być czymś więcej niż zawodową wizytówką. Pomogę Ci spojrzeć na niego oczami rekrutera i podpowiem, jak sprawić, aby lepiej pokazywał, kim jesteś i co możesz zaoferować.',
        action: 'Zapytaj',
      },
      {
        key: 'interview',
        title: 'Indywidualne przygotowanie do rozmowy kwalifikacyjnej',
        meta: '90–150 min · 150 EUR',
        description: 'Masz przed sobą rozmowę kwalifikacyjną? Przygotujmy Cię tak, abyś mógł wejść na nią z większym spokojem, pewnością siebie i świadomością swojej wartości. Połączymy coachingowe wsparcie z moim doświadczeniem w HR i rekrutacji.',
        action: 'Zapytaj',
      },
    ],
    packages: {
      eyebrow: 'PAKIETY',
      title: 'Umów sesje w pakiecie',
      description: 'Jeśli czujesz, że chcesz dać sobie więcej czasu i przestrzeni na zmianę, wybierz pakiet sesji dopasowany do Twoich potrzeb. Możesz zdecydować, ile spotkań będzie dla Ciebie najlepsze i wybrać odpowiadającą Ci opcję cenową.',
      coachingLabel: 'Pakiet coachingowy',
      mentoringLabel: 'Pakiet mentoringowy',
      sessionsLabel: 'sesje',
      action: 'Zapytaj',
      coaching: [
        { count: 2, price: 90 },
        { count: 3, price: 140 },
        { count: 4, price: 185 },
        { count: 5, price: 230 },
      ],
      mentoring: [
        { count: 2, price: 90 },
        { count: 3, price: 140 },
        { count: 4, price: 185 },
        { count: 5, price: 230 },
      ],
    },
  },
} as const;
